// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Post struct {
	ID        string `json:"_id"`
	Title     string `json:"title"`
	Content   string `json:"content"`
	ImageURL  string `json:"imageUrl"`
	Creator   *User  `json:"creator"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type Query struct {
}

type User struct {
	ID     string  `json:"_id"`
	Email  string  `json:"email"`
	Name   string  `json:"name"`
	Status string  `json:"status"`
	Posts  []*Post `json:"posts"`
}

type UserInputData struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Name     string `json:"name"`
}
